# Generated by Django 5.2.10 on 2026-01-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_post_created_at_post_updated_at_profile_grad_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to='profile_images/'),
        ),
    ]
