# Generated by Django 5.2.10 on 2026-01-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_description'),
        ('main_app', '0009_alter_profile_image'),
    ]

    operations = [
    ]
